# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "noairproducts-cedarsphere-1"
client_id = "1d688a4982b6a598caea1ee20bdf858a"
application_url = "https://noairproducts-cedarsphere-1.pages.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://noairproducts-cedarsphere-1.pages.dev/auth/callback",
  "https://noairproducts-cedarsphere-1.pages.dev/auth/shopify/callback",
  "https://noairproducts-cedarsphere-1.pages.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
