api_version = "2024-01"

[[extensions]]
handle = "b2b-order-discount"
# name = "t:name"
# description = "t:description"
name = "Tiered discount"
description = "Custom app by Cedarsphere"

type = "function"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"


  [extensions.ui.paths]
  create = "/app/extensions/b2b-order-discount/:functionId/new"
  details = "/app/extensions/b2b-order-discount/:functionId/:id"


  [extensions.input.variables]
  namespace = "$app:b2b-order-discount"
  key = "function-configuration"
